#!/bin/bash

# Decode Unicode escaped string to UTF-8 string
function decode()
{
  cat | sed -e 's/\\u\(....\)/\&#x\1;/g' | nkf --numchar-input
}

function escape()
{
  cat | sed -e 's/\\"/"/g' -e 's/\\\//\//g' -e 's/\\n/\n/g' 
}

# Get posted media
function get_media()
{
  id=$1
  orig=$2
  tmp=/tmp/$$.media
  param=
  while :; do
    url="https://twitter.com/i/profiles/show/$id/media_timeline$param"
    wget -O - -q "$url" | escape | decode > $tmp
    # video
    grep -Eo '/i/cards/[^"]+' $tmp | sed -e 's/&amp;/\&/' -e 's/^/https:\/\/twitter.com/g' | sort | uniq | \
      wget -O - -i - -q | escape | decode | grep -Eo 'https://video[^&]*'
    # image
    grep -Eo 'https://pbs\.twimg\.com/media/[a-zA-Z0-9_\-]+\.(jpg|png)' $tmp | sort | uniq | \
      (if [ $orig -eq 0 ]; then
        cat
      else
        sed 's/$/:orig/g'
      fi
      )
    cxt_id=$(grep -Eo 'data-tweet-id="[0-9]+' $tmp | sed 's/^.*="//g' | sort | head -n 1)
    [ -n "$cxt_id" ] || break
    max_id=$(expr $cxt_id - 1)
    param="?contextual_tweet_id=$cxt_id&max_id=$max_id"
  done
  rm $tmp
}

function print_usage()
{
  echo "$(basename $0) - The simple twitter media downloader"
  echo ""
  echo "Usage:"
  echo "  $0 [-l] [-d outdir] [-u] twitter_name[, ...]"
  echo ""
  echo "Options:"
  echo "  -l      List up only, No download."
  echo "  -d dir  Set directory to save downloaded files."
  echo "  -u      Create directory named twitter name each by each."
  echo "  -o      Get original size media."
  echo ""
  echo "* You can get more information and latest version at;"
  echo "  berryjack project page : https://github.com/dyama/berryjack"
}

# Initialize varable
dir=.
list_up_only=0
make_user_dir=0
get_orig=0

# Get option strings
while getopts d:lumo opt
do
  case $opt in
    d) dir=$OPTARG ;;
    l) list_up_only=1 ;;
    u) make_user_dir=1 ;;
    o) get_orig=1 ;;
  esac
done
shift $(expr $OPTIND - 1)

# Check number of args and print usage
[ $# -eq 0 ] && print_usage && exit 0

# Download
for id in $@; do
  id=$(basename $id | sed 's/^@//g')
  echo "Target twitter name: $id" 1>&2
  if [ $list_up_only -eq 0 ]; then
    mkdir -p "$dir" 2>/dev/null
    if [ $make_user_dir -eq 1 ]; then
      userdir="$dir/$id"
    else
      userdir="$dir"
    fi
    get_media $id $get_orig | wget -nc -nv -i - -P "$userdir"
  else
    get_media $id $get_orig
  fi
done

